# Generated by Django 4.2.27 on 2026-01-14 12:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_vente', models.DateTimeField(auto_now_add=True, verbose_name='Date de vente')),
                ('montant_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Prix de vente total')),
                ('reduction', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Réduction pour fidélité')),
                ('moyen_paiement', models.CharField(choices=[('CORIS', 'Coris Money'), ('ORANGE', 'Orange Money'), ('MOOV', 'Moov Money'), ('CARD', 'Carte Bancaire')], default='ORANGE', max_length=10, verbose_name='Numéro de téléphone/Carte')),
                ('montant_verse', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Montant reçu')),
                ('montant_rendu', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Monnaie rendue')),
                ('est_payee', models.BooleanField(default=False, verbose_name='Statut du paiement')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Nom du client')),
            ],
            options={
                'verbose_name': 'Commande',
                'verbose_name_plural': 'Commandes',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=50)),
                ('slug', models.SlugField(blank=True, max_length=100, null=True, unique=True)),
                ('categorie', models.CharField(choices=[('TSHIRT', 'tshirt'), ('BASQUET', 'basquet'), ('ORDINATEUR', 'ordinateur'), ('AUTRE', 'autre')], default='TSHIRT', max_length=10, verbose_name='Categorie des produits')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Description détaillée')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products_images', verbose_name='Images du produits')),
                ('prix_achat', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name="Prix d'achat")),
                ('prix_vente', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Prix de vente')),
                ('quantite_stock', models.IntegerField(default=0, verbose_name='Quantité en stock')),
                ('stock_alerte', models.IntegerField(default=10, verbose_name='Seuil en alerte')),
                ('en_solde', models.BooleanField(default=False, verbose_name='Produit en solde')),
                ('pourcentage_solde', models.DecimalField(decimal_places=2, default=0.0, max_digits=4, verbose_name='Pourcentage de réduction')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(default=1)),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='products.order')),
                ('produits', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_recu', models.CharField(editable=False, max_length=20, unique=True)),
                ('moyen_paiement', models.CharField(choices=[('CORIS', 'Coris Money'), ('ORANGE', 'Orange Money'), ('MOOV', 'Moov Money'), ('CARD', 'Carte Bancaire')], default='CASH', max_length=10)),
                ('date_emission', models.DateTimeField(auto_now_add=True)),
                ('commande', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='facture', to='products.order')),
            ],
        ),
    ]
